version: "2.1"

services:
    proxy:
        restart: unless-stopped
        container_name: fastforums_proxy
        image: nginx:latest
        ports:
            - 80:80
        links:
            - rest_api
        depends_on:
            - rest_api
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

    rest_api:
        env_file: rest/.env
        build:
            context: rest
        expose:
            - 5000 # Exposing only to the network
        restart: unless-stopped
        container_name: fastforums_rest
        depends_on:
            postgres:
                condition: service_healthy
        links:
            - postgres

    postgres:
        expose:
            - 5432
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=fastforums
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./.docker/postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        container_name: fastforums_postgres
